// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar(isAuth bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<navbar>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !isAuth {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<ul><header class=\"header\"><div class=\"logo\"><img src=\"/img/logo-oscuro.png\" alt=\"logo_utc\"> <img src=\"/img/Lobitos.png\" alt=\"logo_lobitos\"><div class=\"logo-text\"><h2>Mercado Lobitos UTC</h2><p>\"Emprendimiento con garra\"</p></div></div><nav><ul class=\"nav-links\"><li><a href=\"/\">Inicio</a></li></ul></nav><div class=\"btn\"><span class=\"btn-text\">¿Eres Emprendedor?</span><div class=\"buttons-container\"><a href=\"/auth/login\" class=\"btn-login\">Iniciar Sesión</a> <a href=\"/auth/register\" class=\"btn-register\">Registrarse</a></div></div></header></ul>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<ul><header class=\"header\"><div class=\"logo\"><img src=\"/img/logo-oscuro.png\" alt=\"logo_utc\"> <img src=\"/img/Lobitos.png\" alt=\"logo_lobitos\"><div class=\"logo-text\"><h2>Mercado Lobitos UTC</h2><p>\"Emprendimiento con garra\"</p></div></div><nav><ul class=\"nav-links\"><li><a href=\"/profile\">Ver Perfil</a></li></ul></nav><div class=\"btn\"><div class=\"buttons-container\"><a href=\"/\" class=\"btn-login\">Ir a Homepage</a> <a href=\"/auth/logout\" class=\"btn-register\">Cerrar Sesion</a></div></div></header></ul>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</navbar>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
