// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Organization() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside><div><p>Puesto</p><p>Nombre</p></div><div><p>Puesto</p><p>Nombre</p></div><div><p>+</p><p>Add more colaborators</p></div></aside><section><p>Colaborador</p><img src=\"matricula.jpg\" alt=\"\"><p>Nombre</p><button>Interno</button> <button>Externo</button><form><label for=\"file\">Profile Photo</label> <input type=\"file\" accept=\"image/*\" name=\"file\" id=\"file\"> <label for=\"student_id\">Student ID</label> <input type=\"number\" name=\"student_id\" id=\"student_id\"> <label for=\"middle_names\">Names</label> <input type=\"text\" name=\"middle_names\" id=\"middle_names\"> <label for=\"paternal_surname\">Paternal Surname</label> <input type=\"text\" name=\"paternal_surname\" id=\"paternal_surname\"> <label for=\"maternal_surname\">Maternal Surname</label> <input type=\"text\" name=\"maternal_surname\" id=\"maternal_surname\"> <button type=\"submit\">Create/Update Information</button></form><button>Download your passport</button></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
